### ISSUE TITLE
Missing stop-scrolling.js

### ISSUE THREAD

**Issue by simonepri** [tobernguyen/stop-scrolling-facebook#2]
There's no stop-scrolling.js file in the dist folder

![image](https://user-images.githubusercontent.com/3505087/26847552-c4eb6b44-4afd-11e7-8025-72d7eda65b74.png)

**Comment by tobernguyen** [comment]
@simonepri actually I ignored the file from committing. But I can add it if it is easier for ppl to load the extension without the need of building the project before.

**Comment by tobernguyen** [comment]
Issue fixed. Please check out the latest commit. Cheers 🍻
