### ISSUE TITLE
Broken chrome store link

### ISSUE THREAD

**Issue by simonepri** [tobernguyen/stop-scrolling-facebook#3]
The URL in the README is broken:
![image](https://user-images.githubusercontent.com/3505087/26847670-351929f6-4afe-11e7-87a8-ccd6f11bcabb.png)

https://chrome.google.com/webstore/detail/stop-scrolling-facebook/iceobahpfmegcflceepjpplhhbhdlakk

**Comment by tobernguyen** [comment]
@simonepri thanks for informing me this. I'm aware of this; my app has been removed from the store because of violating policy (having the trademark of Facebook). I'm re-publishing it with a new name and will inform you when it is available.

**Comment by Simbul** [comment]
Hi @tobernguyen. Do you have an idea when you'll be able to re-publish the extension?
I can see you renamed it some days ago, but I can't see it on the Chrome webstore and the one I have installed has stopped working, so I assume something has prevented you from doing it so far.

I think the extension was truly excellent, while it was working: I'd love to be able to keep using it.

**Comment by tobernguyen** [comment]
@Simbul @simonepri 
I have re-published the extension, too bad that I couldn't keep the old link. Here is the new one:

https://chrome.google.com/webstore/detail/stop-scrolling-newsfeed-f/nhcbjhbdnlkddnapaoidpkfbjkpkpdcj?hl=vi&authuser=1

Thanks very much for giving me the motivation to re-publish it 😂

**Comment by simonepri** [comment]
Thank you for the amazing plugin-in

**Comment by tobernguyen** [comment]
You are very welcome!!! Please help me spread the world about this extension, the more people use it, the better it will be!
